image:
  file: .gitpod.Dockerfile

workspaceLocation: 'project'
checkoutLocation: 'project'

tasks:
  - before: |
      sudo rm CHANGELOG.md
      sudo rm coderoad.yaml
      sudo rm tutorial.json
      sudo rm TUTORIAL.md
      sudo touch /workspace/.bash_history
      sudo chmod -R 777 /workspace
      sudo cp /workspace/project/.freeCodeCamp/.bashrc ~/.bashrc
      exit

vscode:
  extensions:
    - CodeRoad.coderoad
