image:
  file: .gitpod.Dockerfile

workspaceLocation: 'project'
checkoutLocation: 'project'

tasks:
  - before: |
      sudo touch /workspace/.bash_history
      sudo chmod -R 777 /workspace
      sudo cp /workspace/project/freeCodeCamp/.bashrc ~/.bashrc
      exit

vscode:
  extensions:
    - CodeRoad.coderoad
